# Utilisez l'image de base Python
FROM python:3.8

# Copiez le code de votre serveur FastAPI dans le conteneur
COPY . .

# Copiez le fichier requirements.txt dans le conteneur
COPY requirements.txt .

# Installez les dépendances Python depuis requirements.txt
RUN pip install -r requirements.txt

# Exposez le port que FastAPI utilise par défaut (8000)
EXPOSE 8000

# Commande pour exécuter votre serveur FastAPI
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
